// Synthetic local HTTP/SQLite acceptance. Invoke directly with Playwright installed.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import {createApp} from '../server/app.mjs';
import {packagePages} from '../scripts/package-pages.mjs';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=resolve(process.env.QA_OUTPUT||`work/lifecycle-browser-${Date.now()}`);
mkdirSync(output,{recursive:true});
const temp=mkdtempSync(join(tmpdir(),'cycling-lifecycle-ui-'));
const publicDir=process.env.QA_USE_PUBLIC==='1'?resolve('public'):packagePages(join(temp,'public'));
const app=createApp({dbPath:join(temp,'synthetic.sqlite'),publicDir});
app.addAdmin('qa-officer','qa-only-password-123');
app.db.prepare('UPDATE settings SET total=6 WHERE id=1').run();
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${app.server.address().port}`;
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
const page=await context.newPage(),officer=await context.newPage();
for(const p of [page,officer])p.setDefaultTimeout(15000);
const errors=[],violations=[],results=[];
for(const p of [page,officer])p.on('pageerror',e=>errors.push(e.message));
const staffRequests=[];officer.on('response',response=>{if(response.url().endsWith('/api/admin/lifecycle')){const body=response.request().postDataJSON();staffRequests.push({action:body.action,status:response.status()});}});
await context.addInitScript(()=>document.addEventListener('securitypolicyviolation',e=>window.__violations=(window.__violations||[]).concat(`${e.effectiveDirective}:${e.blockedURI}`)));
const waitText=(p,selector,text)=>p.locator(selector).filter({hasText:text}).waitFor();
const taipeiInput=(d)=>new Date(d.getTime()+8*3600000).toISOString().slice(0,16);
const taipeiWeekLabel=()=>{const local=new Date(Date.now()+8*3600000),weekday=(local.getUTCDay()+6)%7;const monday=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate()-weekday)-8*3600000);const display=d=>new Date(d).toLocaleDateString('zh-TW',{month:'numeric',day:'numeric',timeZone:'Asia/Taipei'});return `${display(monday)}—${display(+monday+6*86400000)}`;};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9YPg2VMAAAAASUVORK5CYII=','base64');
const latest=()=>app.db.prepare('SELECT id,status,approval FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1').get();
async function layout(p,label,width){await p.setViewportSize({width,height:900});await p.screenshot({path:join(output,`${label}.png`),fullPage:true});if(width<=390){await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:join(output,`${label}-fold.png`),fullPage:false});}const overflow=await p.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('*')].map(el=>({tag:el.tagName,id:el.id,cls:el.className?.baseVal??el.className,right:Math.round(el.getBoundingClientRect().right),width:Math.round(el.getBoundingClientRect().width)})).filter(x=>x.right>innerWidth+1).sort((a,b)=>b.right-a.right).slice(0,8)}));assert.ok(overflow.scrollWidth<=width,`${label} horizontal overflow: ${JSON.stringify(overflow)}`);results.push(`${label}: no horizontal overflow`);await p.setViewportSize({width:1280,height:900});}
async function officerLogin(){await officer.goto(base+'/admin.html');await officer.locator('#login-form [name=username]').fill('qa-officer');await officer.locator('#login-form [name=password]').fill('qa-only-password-123');await officer.locator('#login-form button[type=submit]').click();await officer.locator('#lc-admin:not([hidden])').waitFor();}
const tab=name=>officer.getByRole('tab',{name}).click();
async function apply(){await page.goto(base+'/index.html');await waitText(page,'#lc-calendar','QA-BIKE');await page.locator('.lc-asset').filter({hasText:'QA-BIKE'}).getByRole('button',{name:'選這台車'}).click();const start=new Date(Date.now()+3*3600000),end=new Date(Date.now()+5*3600000);await page.locator('#lc-start').fill(taipeiInput(start));await page.locator('#lc-end').fill(taipeiInput(end));await page.locator('#lc-accessories input').check();const previousAccessory=await page.locator('#lc-accessories input').elementHandle();await page.locator('#lc-refresh').click();await previousAccessory.waitForElementState('hidden');assert.equal(await page.locator('#lc-accessories input').isChecked(),true);
 await page.locator('#lc-student').fill('qa20261009');await page.locator('#lc-name').fill('合成測試社員');const count=()=>app.db.prepare('SELECT COUNT(*) n FROM lifecycle_reservations').get().n,before=count();await page.locator('#lc-reserve-form button[type=submit]').click();await waitText(page,'#lc-reserve-message','Instagram');assert.equal(count(),before,'Instagram acknowledgement is required before submitting');
 await page.locator('#lc-ig-ack').check();await page.locator('#lc-reserve-form button[type=submit]').click();await waitText(page,'#lc-reserve-message','等待幹部同意');const row=latest();assert.equal(row.approval,'pending');assert.equal(app.db.prepare('SELECT COUNT(*) n FROM lifecycle_reservation_assets WHERE reservationId=?').get(row.id).n,2);await waitText(page,'#lc-records','待幹部同意');assert.equal(await page.locator('#lc-records').getByRole('button',{name:'前往取車檢查'}).count(),0);app.db.prepare('UPDATE lifecycle_reservations SET start=? WHERE id=?').run(new Date(Date.now()-60000).toISOString(),row.id);results.push('Student ID/name application held both assets and waits for officer approval');return row.id;}
async function approve(){await officerLogin();await waitText(officer,'#lc-todo','待同意預約');await waitText(officer,'#lc-todo','QA20261009');await officer.locator('#lc-todo').getByRole('button',{name:'同意預約'}).click();await officer.locator('#lc-todo').getByRole('button',{name:'同意預約',exact:true}).waitFor({state:'detached'});assert.equal(latest().approval,'approved');await page.reload();await waitText(page,'#lc-records','已預約');results.push('Officer approved; member device sees pickup enabled');}
async function photos(phase){for(const slot of ['left','right','drivetrain','damage']){await page.locator(`#lc-photo-inputs input[data-slot=${slot}]`).setInputFiles({name:`${phase}-${slot}.png`,mimeType:'image/png',buffer:png});await page.locator(`#lc-photo-inputs [data-slot-card=${slot}][data-state=done]`).filter({hasText:'已上傳'}).waitFor();}assert.equal(app.db.prepare('SELECT COUNT(*) n FROM lifecycle_photos WHERE phase=?').get(phase).n>=4,true);}
async function checks(){for(const key of ['frame','tires','brakes','gears','accessories'])await page.locator(`#lc-flow-form [name=${key}][value=ok]`).check();}
async function sign(){await page.locator('#lc-flow-form [name=accepted]').check();await page.locator('#lc-flow-form [name=signatureName]').fill('合成測試社員');const canvas=page.locator('#lc-signature');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();await page.mouse.move(box.x+30,box.y+Math.min(100,box.height/2));await page.mouse.down();await page.mouse.move(box.x+180,box.y+Math.min(60,box.height/3),{steps:20});await page.mouse.move(box.x+Math.min(330,box.width-20),box.y+Math.min(95,box.height/2),{steps:20});await page.mouse.up();}
async function pickup(){await page.locator('#lc-records .lc-record').first().getByRole('button',{name:'前往取車檢查'}).click();await photos('pickup');await checks();await sign();await page.locator('#lc-flow-form button[type=submit]').click();await waitText(page,'#lc-member-message','借用正式開始');assert.equal(latest().status,'in_use');}
try{
 await officerLogin();results.push('Officer session shared with lifecycle workspace');
 await waitText(officer,'#lc-todo','預約開放前檢查');results.push('Officer to-do shows setup checklist before booking opens');
 await tab('取車規範');for(const [name,value] of [['location','合成測試社辦'],['instructions','請於合成測試車庫拍照'],['terms','合成測試規範：取還車須檢查並留存車況。']])await officer.locator(`#lc-policy-form [name=${name}]`).fill(value);await officer.locator('#lc-policy-form button[type=submit]').click();await officer.waitForFunction(()=>document.querySelector('#lc-current-version')?.title?.length===64);
 await tab('車輛配件');for(const [code,name,kind] of [['QA-BIKE','合成測試車','bike'],['QA-HELMET','合成安全帽','accessory']]){await officer.locator('#lc-asset-form [name=code]').fill(code);await officer.locator('#lc-asset-form [name=name]').fill(name);await officer.locator('#lc-asset-form [name=kind]').selectOption(kind);await officer.locator('#lc-asset-form [name=state]').selectOption('available');await officer.locator('#lc-asset-form [name=reason]').fill('合成盤點');await officer.locator('#lc-asset-form button[type=submit]').click();await waitText(officer,'#lc-fleet',code);}
 assert.equal(await officer.locator('#lc-todo').filter({hasText:'預約開放前檢查'}).count(),0);results.push('Officer published policy and inventoried bike and accessory; no member credential needed');
 await officer.locator('#logout').click();await officer.locator('#workspace').waitFor({state:'hidden'});assert.equal(await officer.locator('#lc-admin').isVisible(),false);results.push('Officer logout cleared private workspace');
 await apply();await approve();await pickup();results.push('Approved booking: four pickup photos, checklist, signature and actual pickup on the same device');
 await page.locator('#lc-records').getByRole('button',{name:'開始還車'}).click();await photos('return');await checks();await page.locator('#lc-flow-form button[type=submit]').click();await waitText(page,'#lc-member-message','歸還已結案');assert.equal(latest().status,'returned');results.push('Four return photos and normal return closed the booking');
 await page.locator('#lc-records').getByRole('button',{name:'比較借還照片'}).click();await page.locator('#lc-comparison img').nth(7).waitFor();assert.equal(await page.locator('#lc-comparison img').count(),8);await layout(page,'member-desktop',1280);await layout(page,'member-mobile',360);results.push('Photo comparison and responsive member layout');
 let photoStarted,photoRelease;const photoSeen=new Promise(resolve=>photoStarted=resolve),photoGate=new Promise(resolve=>photoRelease=resolve);await page.route('**/api/lifecycle',async route=>{const body=JSON.parse(route.request().postData()||'{}');if(body.action!=='photo_read'){await route.continue();return;}const response=await route.fetch();photoStarted();await photoGate;await route.fulfill({response});});await page.locator('#lc-records').getByRole('button',{name:'比較借還照片'}).click();await photoSeen;await page.locator('#lc-transfer summary').click();await page.locator('#lc-token-clear').click();photoRelease();await page.unrouteAll({behavior:'wait'});assert.equal(await page.locator('#lc-comparison img').count(),0);await waitText(page,'#lc-records','還沒有借車紀錄');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('lc-booking-keys')||'[]')),[]);results.push('Removing bookings from the device clears records; a delayed private photo cannot reappear');
 await apply();await approve();await pickup();
 await officerLogin();await tab('預約紀錄');officer.once('dialog',d=>d.accept());await officer.locator('#lc-bookings').getByRole('button',{name:'重新產生取還車碼'}).click();await officer.locator('#lc-bookings .lc-token-value').waitFor();const code=(await officer.locator('#lc-bookings .lc-token-value').textContent()).trim();assert.match(code,/^[a-f0-9]{64}$/);
 await page.reload();await waitText(page,'#lc-records','還沒有借車紀錄');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('lc-booking-keys')||'[]')),[],'replaced key is forgotten');
 await page.locator('#lc-transfer summary').click();await page.locator('#lc-token').fill(`幹部訊息：${code}`);await waitText(page,'#lc-member-message','已把這筆借車加入');await waitText(page,'#lc-records','使用中');results.push('Officer reissued a booking code; old device key stopped working and the new code restored access');
 await page.locator('#lc-records .lc-record').first().getByRole('button',{name:'開始還車'}).click();await photos('return');await checks();await page.locator('#lc-flow-form [name=brakes][value=bad]').check();await page.locator('#lc-missing').filter({hasText:'車況備註'}).waitFor();await page.locator('#lc-flow-form [name=notes]').fill('合成測試：煞車異音');await page.locator('#lc-flow-form button[type=submit]').click();await waitText(page,'#lc-member-message','幹部檢查');assert.equal(latest().status,'inspection');results.push('Abnormal return quarantined bike and created officer notification');
 await tab('待辦');await officer.locator('#lc-admin-refresh').click();await waitText(officer,'#lc-todo','還車回報異常：煞車');await officer.locator('#lc-todo').getByRole('button',{name:'完成異常審核'}).click();await officer.locator('#lc-todo .lc-inline-form textarea').fill('測試檢修完成');await officer.locator('#lc-todo .lc-inline-form input[value=available]').check();await officer.locator('#lc-todo .lc-inline-form').getByRole('button',{name:'確認結案'}).click();await officer.waitForFunction(()=>!document.querySelector('#lc-todo')?.textContent?.includes('完成異常審核'));assert.equal(latest().status,'returned');await layout(officer,'officer-desktop',1280);await layout(officer,'officer-mobile',360);results.push('Officer reviewed abnormal return and restored bike');
 await tab('借用人');await officer.locator('#lc-members').getByRole('button',{name:'編輯'}).click();await officer.locator('#lc-member-form [name=active]').uncheck();await officer.locator('#lc-member-form [name=contact]').fill('qa-only');await officer.locator('#lc-member-form [name=reason]').fill('合成停權測試');await officer.locator('#lc-member-form button[type=submit]').click();await waitText(officer,'#lc-members','已停用');
 const blocked=await page.request.post(base+'/api/lifecycle',{data:{action:'apply',token:null,payload:{requestId:randomUUID(),studentId:'QA20261009',name:'合成測試社員',assetIds:[app.db.prepare("SELECT id FROM lifecycle_assets WHERE code='QA-BIKE'").get().id],start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+90000000).toISOString(),key:randomBytes(32).toString('hex')}}});assert.equal(blocked.status(),403);results.push('Officer blocked a student ID; new applications from it are refused');
 const remoteContext=await browser.newContext({timezoneId:'America/Los_Angeles',viewport:{width:390,height:820}});const remotePage=await remoteContext.newPage();await remotePage.goto(base+'/index.html');await remotePage.locator('#lc-week-label').filter({hasText:taipeiWeekLabel()}).waitFor();const remoteStart=await remotePage.locator('#lc-start').inputValue();const soon=new Date(Math.ceil((Date.now()+3600000)/1800000)*1800000);assert.equal(remoteStart.slice(0,10),taipeiInput(soon).slice(0,10),'default start follows Taipei time, rolling to tomorrow late at night');await remoteContext.close();results.push('Calendar week and default reservation date remain Asia/Taipei on a Los Angeles device');
 await page.goto(base+'/index.html');await page.locator('[data-language=en]').click();await page.locator('#lc-reserve-heading').filter({hasText:'Choose pickup and return times'}).waitFor();const leftover=await page.evaluate(()=>{const cjk=/[㐀-鿿]/,found=[];for(const id of ['lc-main']){const walker=document.createTreeWalker(document.getElementById(id),NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const t=n.data.trim();if(t&&cjk.test(t.replace(/合成[^\s·]*/g,''))&&!n.parentElement.closest('.lc-asset-head strong'))found.push(t);}}return found;});assert.deepEqual(leftover,[],'member booking UI has untranslated text in English mode');await page.locator('[data-language=zh]').click();await page.locator('#lc-reserve-heading').filter({hasText:'選擇借還時間'}).waitFor();results.push('Member booking UI fully switches to English and back');
 for(const p of [page,officer])violations.push(...await p.evaluate(()=>window.__violations||[]));assert.deepEqual(errors,[]);assert.deepEqual(violations,[]);results.push('No page errors or CSP violations');
 writeFileSync(join(output,'results.json'),JSON.stringify({scope:'synthetic local HTTP and SQLite; clock fixture adjusts reservation start for pickup window',results,errors,violations},null,2));console.log(results.join('\n'));
}catch(e){await page.screenshot({path:join(output,'failure.png'),fullPage:true});await officer.screenshot({path:join(output,'failure-officer.png'),fullPage:true}).catch(()=>{});console.error('QA failure:',e);console.error({staffRequests,errors});console.error((await page.locator('body').innerText()).slice(0,3000));process.exitCode=1;}
finally{await browser.close();app.server.closeAllConnections();await app.close();}
