// Synthetic local HTTP/SQLite acceptance. Invoke directly with Playwright installed.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createApp} from '../server/app.mjs';
import {packagePages} from '../scripts/package-pages.mjs';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=resolve(process.env.QA_OUTPUT||`work/lifecycle-browser-${Date.now()}`);
mkdirSync(output,{recursive:true});
const temp=mkdtempSync(join(tmpdir(),'cycling-lifecycle-ui-'));
const publicDir=process.env.QA_USE_PUBLIC==='1'?resolve('public'):packagePages(join(temp,'public'));
const app=createApp({dbPath:join(temp,'synthetic.sqlite'),publicDir});
app.addAdmin('qa-officer','qa-only-password-123');
app.db.prepare('UPDATE settings SET total=6 WHERE id=1').run();
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${app.server.address().port}`;
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true});
page.setDefaultTimeout(15000);
const errors=[],violations=[],results=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>document.addEventListener('securitypolicyviolation',e=>window.__violations=(window.__violations||[]).concat(`${e.effectiveDirective}:${e.blockedURI}`)));
const waitText=(selector,text)=>page.locator(selector).filter({hasText:text}).waitFor();
const fill=(form,name,value)=>page.locator(`${form} [name="${name}"]`).fill(value);
const taipeiInput=(d)=>new Date(d.getTime()+8*3600000).toISOString().slice(0,16);
const taipeiWeekLabel=()=>{const local=new Date(Date.now()+8*3600000),weekday=(local.getUTCDay()+6)%7;const monday=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate()-weekday)-8*3600000);const display=d=>new Date(d).toLocaleDateString('zh-TW',{month:'numeric',day:'numeric',timeZone:'Asia/Taipei'});return `${display(monday)}—${display(+monday+6*86400000)}`;};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9YPg2VMAAAAASUVORK5CYII=','base64');
async function layout(label,width){await page.setViewportSize({width,height:900});await page.screenshot({path:join(output,`${label}.png`),fullPage:true});if(width<=390){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:join(output,`${label}-fold.png`),fullPage:false});}const overflow=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,offenders:[...document.querySelectorAll('*')].map(el=>({tag:el.tagName,id:el.id,cls:el.className?.baseVal??el.className,right:Math.round(el.getBoundingClientRect().right),width:Math.round(el.getBoundingClientRect().width)})).filter(x=>x.right>innerWidth+1).sort((a,b)=>b.right-a.right).slice(0,8)}));assert.ok(overflow.scrollWidth<=width,`${label} horizontal overflow: ${JSON.stringify(overflow)}`);results.push(`${label}: no horizontal overflow`);}
async function reserve(token){await page.goto(base+'/index.html');await waitText('#lc-calendar','QA-BIKE');await page.locator('#lc-token').fill(token);await page.locator('#lc-token-form button[type=submit]').click();await waitText('#lc-member-message','已取得');await page.locator('.lc-asset').filter({hasText:'QA-BIKE'}).getByRole('button',{name:'選這台車'}).click();const start=new Date(Date.now()+3*3600000),end=new Date(Date.now()+5*3600000);await page.locator('#lc-start').fill(taipeiInput(start));await page.locator('#lc-end').fill(taipeiInput(end));await page.locator('#lc-reserve-form button[type=submit]').click();await waitText('#lc-reserve-message','預約成功');assert.match(await page.locator('#lc-records').textContent(),/已預約/);const row=app.db.prepare("SELECT id FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1").get();app.db.prepare('UPDATE lifecycle_reservations SET start=? WHERE id=?').run(new Date(Date.now()-60000).toISOString(),row.id);return row.id;}
async function photos(phase){for(const slot of ['left','right','drivetrain','damage']){await page.locator(`#lc-photo-inputs input[data-slot=${slot}]`).setInputFiles({name:`${phase}-${slot}.png`,mimeType:'image/png',buffer:png});const label=slot==='left'?'左側全景':slot==='right'?'右側全景':slot==='drivetrain'?'傳動系統':'損傷部位';await page.locator('#lc-uploaded li').filter({hasText:label}).filter({hasText:'已上傳'}).waitFor();}assert.equal(app.db.prepare('SELECT COUNT(*) n FROM lifecycle_photos WHERE phase=?').get(phase).n>=4,true);}
async function checks(){for(const key of ['frame','tires','brakes','gears','accessories'])await page.locator(`#lc-flow-form [name=${key}]`).check();}
async function sign(){await page.locator('#lc-flow-form [name=accepted]').check();await fill('#lc-flow-form','signatureName','合成測試社員');const canvas=page.locator('#lc-signature');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();await page.mouse.move(box.x+30,box.y+Math.min(100,box.height/2));await page.mouse.down();await page.mouse.move(box.x+180,box.y+Math.min(60,box.height/3),{steps:20});await page.mouse.move(box.x+Math.min(330,box.width-20),box.y+Math.min(95,box.height/2),{steps:20});await page.mouse.up();}
try{
 await page.goto(base+'/admin.html');await fill('#login-form','username','qa-officer');await fill('#login-form','password','qa-only-password-123');await page.locator('#login-form button[type=submit]').click();await page.locator('#lc-admin:not([hidden])').waitFor();results.push('Officer session shared with lifecycle workspace');
 await fill('#lc-policy-form','location','合成測試社辦');await fill('#lc-policy-form','instructions','請於合成測試車庫拍照');await fill('#lc-policy-form','terms','合成測試規範：取還車須檢查並留存車況。');await page.locator('#lc-policy-form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#lc-current-version')?.textContent?.length===64);
 await fill('#lc-asset-form','code','QA-BIKE');await fill('#lc-asset-form','name','合成測試車');await page.locator('#lc-asset-form [name=kind]').selectOption('bike');await page.locator('#lc-asset-form [name=state]').selectOption('available');await fill('#lc-asset-form','reason','合成車盤點');await page.locator('#lc-asset-form button[type=submit]').click();await waitText('#lc-admin-data','QA-BIKE');
 await fill('#lc-member-form','studentId','QA20261008');await fill('#lc-member-form','name','合成測試社員');await fill('#lc-member-form','contact','qa-only');await fill('#lc-member-form','validUntil',taipeiInput(new Date(Date.now()+20*86400000)));await fill('#lc-member-form','reason','合成身分核對');await page.locator('#lc-member-form button[type=submit]').click();await page.locator('#lc-new-token:not([hidden])').waitFor();const token=(await page.locator('#lc-new-token').textContent()).match(/[a-f0-9]{64}/)[0];assert.equal(token.length,64);results.push('Officer created policy, bike, member; one-time token issued');
 await page.locator('#logout').click();await page.locator('#workspace').waitFor({state:'hidden'});assert.equal(await page.locator('#lc-admin').isVisible(),false);assert.equal(await page.locator('#lc-new-token').textContent(),'');results.push('Officer logout cleared private workspace and issued token');
 await reserve(token);await page.locator('#lc-records').getByRole('button',{name:'前往取車檢查'}).click();await photos('pickup');await checks();await sign();await page.locator('#lc-flow-form button[type=submit]').click();await waitText('#lc-member-message','借用正式開始');assert.equal(app.db.prepare("SELECT status FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1").get().status,'in_use');results.push('Reservation, four original pickup photos, checklist, signature and actual pickup');
 await page.locator('#lc-records').getByRole('button',{name:'開始還車'}).click();await photos('return');await checks();await page.locator('#lc-flow-form button[type=submit]').click();await waitText('#lc-member-message','歸還已結案');assert.equal(app.db.prepare("SELECT status FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1").get().status,'returned');results.push('Four return photos and normal return closed the reservation');
 await page.locator('#lc-records').getByRole('button',{name:'比較借還照片'}).click();await page.locator('#lc-comparison img').nth(7).waitFor();assert.equal(await page.locator('#lc-comparison img').count(),8);await layout('member-desktop',1280);await layout('member-mobile',360);await page.locator('#lc-token-clear').click();assert.equal(await page.locator('#lc-records').textContent(),'');assert.equal(await page.locator('#lc-comparison img').count(),0);results.push('Photo comparison, responsive member layout and token clear privacy');
 await page.locator('#lc-token').fill(token);await page.locator('#lc-token-form button[type=submit]').click();await waitText('#lc-member-message','已取得');let photoStarted,photoRelease;const photoSeen=new Promise(resolve=>photoStarted=resolve),photoGate=new Promise(resolve=>photoRelease=resolve);await page.route('**/api/lifecycle',async route=>{const body=JSON.parse(route.request().postData()||'{}');if(body.action!=='photo_read'){await route.continue();return;}const response=await route.fetch();photoStarted();await photoGate;await route.fulfill({response});});await page.locator('#lc-records').getByRole('button',{name:'比較借還照片'}).click();await photoSeen;await page.locator('#lc-token-clear').click();photoRelease();await page.unrouteAll({behavior:'wait'});assert.equal(await page.locator('#lc-comparison img').count(),0);assert.equal(await page.locator('#lc-records').textContent(),'');results.push('Delayed private photo response cannot reappear after token clear');
 await reserve(token);await page.locator('#lc-records .lc-record').first().getByRole('button',{name:'前往取車檢查'}).click();await photos('pickup');await checks();await sign();await page.locator('#lc-flow-form button[type=submit]').click();await waitText('#lc-member-message','借用正式開始');await page.locator('#lc-records .lc-record').first().getByRole('button',{name:'開始還車'}).click();await photos('return');await checks();await page.locator('#lc-flow-form [name=brakes]').uncheck();await page.locator('#lc-flow-form button[type=submit]').click();await waitText('#lc-member-message','幹部檢查');assert.equal(app.db.prepare("SELECT status FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1").get().status,'inspection');results.push('Abnormal return quarantined bike and created officer notification');
 await page.goto(base+'/admin.html');await fill('#login-form','username','qa-officer');await fill('#login-form','password','qa-only-password-123');await page.locator('#login-form button[type=submit]').click();await page.locator('#lc-admin:not([hidden])').waitFor();await waitText('#lc-admin-data','待處理異常');const dialogs=['測試檢修完成','available'];page.on('dialog',async d=>d.accept(dialogs.shift()));await page.locator('#lc-admin-data').getByRole('button',{name:'完成異常審核'}).click();await page.waitForFunction(()=>!document.querySelector('#lc-admin-data')?.textContent?.includes('完成異常審核'));assert.equal(app.db.prepare("SELECT status FROM lifecycle_reservations ORDER BY createdAt DESC LIMIT 1").get().status,'returned');await layout('officer-desktop',1280);await layout('officer-mobile',360);results.push('Officer reviewed abnormal return and restored bike');
 const memberSection=page.locator('#lc-admin-data .lc-admin-section').filter({has:page.getByRole('heading',{name:'社員資格',exact:true})});await memberSection.getByRole('button',{name:'編輯'}).click();await page.locator('#lc-member-form [name=reissue]').check();await fill('#lc-member-form','reason','合成測試補發');await page.locator('#lc-member-form button[type=submit]').click();await waitText('#lc-new-token','舊碼已失效');const replacement=(await page.locator('#lc-new-token').textContent()).match(/[a-f0-9]{64}/)[0];assert.notEqual(replacement,token);const oldRead=await page.request.post(base+'/api/lifecycle',{data:{action:'me',token,payload:{}}});const newRead=await page.request.post(base+'/api/lifecycle',{data:{action:'me',token:replacement,payload:{}}});assert.equal(oldRead.status(),401);assert.equal(newRead.status(),200);results.push('Officer reissued credential; old token revoked and new token works');
 const remoteContext=await browser.newContext({timezoneId:'America/Los_Angeles',viewport:{width:390,height:820}});const remotePage=await remoteContext.newPage();await remotePage.goto(base+'/index.html');await remotePage.locator('#lc-week-label').filter({hasText:taipeiWeekLabel()}).waitFor();const remoteStart=await remotePage.locator('#lc-start').inputValue();assert.equal(remoteStart.slice(0,10),taipeiInput(new Date()).slice(0,10));await remoteContext.close();results.push('Calendar week and default reservation date remain Asia/Taipei on a Los Angeles device');
 violations.push(...await page.evaluate(()=>window.__violations||[]));assert.deepEqual(errors,[]);assert.deepEqual(violations,[]);results.push('No page errors or CSP violations');
 writeFileSync(join(output,'results.json'),JSON.stringify({scope:'synthetic local HTTP and SQLite; clock fixture adjusts reservation start for pickup window',results,errors,violations},null,2));console.log(results.join('\n'));
}catch(e){await page.screenshot({path:join(output,'failure.png'),fullPage:true});console.error('QA failure:',e);console.error((await page.locator('body').innerText()).slice(0,4000));process.exitCode=1;}
finally{await browser.close();app.server.closeAllConnections();await app.close();}
