import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

test('Production SQL on embedded PostgreSQL: grants, identity, queue, retry, inventory',async()=>{
 const db=new PGlite();
 const president='00000000-0000-4000-8000-000000000001';
 const vice='00000000-0000-4000-8000-000000000002';
 const outsider='00000000-0000-4000-8000-000000000003';
 const rpc=async(sql,args=[]) => (await db.query(`select ${sql} as result`,args)).rows[0].result;
 const as=async(role,id='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);};
 const register=async(student,token,type='line')=>rpc('public.register($1,$2,$3,$4,$5)',[student,'Test member',type,'test-only',token]);
 try{
 await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key, email text); create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
 await db.exec(readFileSync(new URL('../supabase/migrations/001_borrow.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users(id,email) values($1,$4),($2,$5),($3,$6)',[president,vice,outsider,'president@example.test','vice@example.test','outsider@example.test']);
 await db.query('insert into private.admins(user_id) values($1),($2)',[president,vice]);
 const functions=(await db.query("select proname,prosecdef,proconfig from pg_proc join pg_namespace n on n.oid=pronamespace where n.nspname='public' and proname in ('summary','register','lookup','admin_records','admin_action','admin_settings')")).rows;
 assert.equal(functions.length,6);assert.ok(functions.every(f=>f.prosecdef&&f.proconfig.some(c=>c==='search_path=""')));
 assert.equal((await db.query("select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relkind='r' and c.relrowsecurity")).rows[0].n,4);
 await db.exec(readFileSync(new URL('../supabase/migrations/002_opening_loans.sql',import.meta.url),'utf8'));
 await db.exec(readFileSync(new URL('../supabase/migrations/003_abuse_controls.sql',import.meta.url),'utf8'));
 await as('anon');assert.equal((await rpc('public.summary()')).total,null);
 for(const table of ['records','settings','admins','audit'])await assert.rejects(db.query(`select * from private.${table}`),/permission denied/);
 for(const fn of ['public.admin_records()','public.admin_settings(1,\'\')','public.admin_action(1,\'lend\',null)'])await assert.rejects(rpc(fn),/permission denied/);
 await assert.rejects(register('A','a'.repeat(64)),/尚未設定/);
 await as('authenticated',outsider);await assert.rejects(rpc('public.admin_records()'),/管理員/);await assert.rejects(rpc("public.admin_settings(1,'')"),/管理員/);await assert.rejects(rpc("public.admin_action(1,'lend',null)"),/管理員/);
 await as('authenticated',president);await rpc("public.admin_settings(1,'')");
 await as('anon');const a=await register(' a ','a'.repeat(64)),b=await register('B','b'.repeat(64));
 assert.equal(a.record.studentId,'A');assert.equal(a.record.position,1);assert.equal(b.record.standby,1);
 assert.equal((await register('A','a'.repeat(64))).record.id,a.record.id);
 await assert.rejects(register('a','c'.repeat(64)),/已有有效/);await assert.rejects(register('C','c'.repeat(64),'email'),/聯絡方式/);
 await assert.rejects(rpc('public.lookup($1)',['d'.repeat(64)]),/查無登記/);await assert.rejects(rpc('public.lookup($1)',['1']),/格式/);
 assert.equal((await rpc('public.lookup($1)',['a'.repeat(64)])).record.id,a.record.id);
 assert.ok(!JSON.stringify(await rpc('public.summary()')).includes('studentId'));
 await as('authenticated',vice);const lend=()=>rpc('public.admin_action($1,$2,$3)',[b.record.id,'lend','test bicycle']);
 await lend();await lend();await assert.rejects(rpc('public.admin_action($1,$2,$3)',[a.record.id,'lend',null]),/沒有尚未借出/);
 await assert.rejects(rpc("public.admin_settings(0,'')"),/低於/);
 await as('anon');await assert.rejects(register('b','c'.repeat(64)),/已有有效/);const me=await rpc('public.lookup($1)',['a'.repeat(64)]);assert.equal(me.record.position,1);assert.equal(me.record.standby,1);
 await as('authenticated',president);await rpc('public.admin_action($1,$2,$3)',[b.record.id,'return',null]);await rpc('public.admin_action($1,$2,$3)',[b.record.id,'return',null]);
 assert.equal((await rpc('public.summary()')).available,1);
 await rpc('public.admin_action($1,$2,$3)',[a.record.id,'cancel',null]);await rpc('public.admin_action($1,$2,$3)',[a.record.id,'cancel',null]);
 await assert.rejects(rpc('public.admin_action($1,$2,$3)',[a.record.id,'return',null]),/狀態不允許/);
 const all=await rpc('public.admin_records()');assert.equal(all.summary.waiting,0);assert.equal(all.summary.borrowed,0);
 assert.equal(all.records.length,2);assert.ok(!JSON.stringify(all).includes('token_hash'));
 assert.equal(all.audit.filter(a=>a.action==='lend').length,1);assert.equal(all.audit.filter(a=>a.action==='return').length,1);assert.equal(all.audit.filter(a=>a.action==='cancel').length,1);
 assert.equal(all.audit.find(a=>a.action==='lend').actor,'vice@example.test');assert.equal(all.audit.find(a=>a.action==='lend').actorId,vice);assert.equal(all.audit.find(a=>a.action==='return').actor,'president@example.test');
 await as('authenticated',outsider);await assert.rejects(db.query('select * from private.records'),/permission denied/);
 await as('anon');assert.equal((await rpc('public.lookup($1)',['b'.repeat(64)])).record.status,'returned');
 await assert.rejects(rpc("public.admin_return_opening(1,'00000000-0000-4000-8000-000000000010')"),/permission denied/);
 await db.exec('reset role');await db.exec("update private.opening_loans set outstanding=3,expected_return='2000-01-01',note='test inventory' where id=1");
 await as('authenticated',president);await rpc("public.admin_settings(6,'')");
 assert.equal((await rpc('public.summary()')).borrowed,3);
 assert.equal((await rpc('public.admin_records()')).opening.expectedReturn,'2000-01-01');
 await as('anon');const openingQueue=[];for(let i=0;i<4;i++)openingQueue.push(await register(`OPEN${i}`,String(i+1).repeat(64)));
 assert.equal(openingQueue[3].record.standby,1);
 await as('authenticated',president);for(const r of openingQueue.slice(0,3))await rpc('public.admin_action($1,$2,$3)',[r.record.id,'lend',null]);
 await assert.rejects(rpc('public.admin_action($1,$2,$3)',[openingQueue[3].record.id,'lend',null]),/沒有尚未借出/);
 await assert.rejects(rpc("public.admin_settings(5,'')"),/低於/);
 const requestId='00000000-0000-4000-8000-000000000010';
 const returned=await rpc('public.admin_return_opening($1,$2)',[1,requestId]);
 assert.equal(returned.summary.borrowed,5);assert.equal(returned.opening.outstanding,2);
 const retry=await rpc('public.admin_return_opening($1,$2)',[1,requestId]);assert.deepEqual(retry.receipt,returned.receipt);assert.equal(retry.summary.borrowed,5);
 await assert.rejects(rpc('public.admin_return_opening($1,$2)',[2,requestId]),/不同歸還數量/);
 await assert.rejects(rpc('public.admin_return_opening($1,$2)',[3,'00000000-0000-4000-8000-000000000011']),/不可超過/);
 const openingAdmin=await rpc('public.admin_records()');assert.equal(openingAdmin.audit.filter(a=>a.action==='opening-return').length,1);assert.equal(openingAdmin.audit.find(a=>a.action==='opening-return').details.requestId,requestId);
 await as('authenticated',outsider);await assert.rejects(rpc('public.admin_return_opening($1,$2)',[1,requestId]),/管理員/);
 await as('anon');await assert.rejects(db.query('select * from private.opening_loans'),/permission denied/);await assert.rejects(db.query('select * from private.opening_returns'),/permission denied/);
 assert.ok(!JSON.stringify(await rpc('public.summary()')).includes('expectedReturn'));
 // 003: anonymous registration throttle, officer bulk cancel, audited export.
 await as('anon');for(const fn of ['public.admin_cancel_many(array[1]::bigint[])','public.admin_export()'])await assert.rejects(rpc(fn),/permission denied/);
 await as('authenticated',outsider);await assert.rejects(rpc('public.admin_cancel_many(array[1]::bigint[])'),/管理員/);await assert.rejects(rpc('public.admin_export()'),/管理員/);
 await db.exec('reset role');assert.equal((await db.query("select count(*)::int n from private.register_attempts where client_hash='unknown'")).rows[0].n,(await db.query('select count(*)::int n from private.register_attempts')).rows[0].n);
 await db.exec("insert into private.register_attempts(client_hash) select 'test-flood' from generate_series(1,15)");
 await as('anon');await assert.rejects(register('FLOOD','e'.repeat(64)),/人數較多/);
 assert.equal((await register('OPEN0','1'.repeat(64))).record.studentId,'OPEN0'); // replay of an existing code is never throttled
 await db.exec('reset role');await db.exec("delete from private.register_attempts");
 await db.query("select set_config('request.headers',$1,false)",[JSON.stringify({'cf-connecting-ip':'203.0.113.9','x-forwarded-for':'198.51.100.1, 203.0.113.9'})]);
 await db.exec("insert into private.register_attempts(client_hash) select encode(sha256(convert_to('203.0.113.9','UTF8')),'hex') from generate_series(1,10)");
 await as('anon');await assert.rejects(register('FLOOD','e'.repeat(64)),/次數過多/);
 await db.query("select set_config('request.headers',$1,false)",[JSON.stringify({'cf-connecting-ip':'203.0.113.10'})]);
 const x1=await register('X1','f'.repeat(64)),x2=await register('X2','a1'.repeat(32));
 await db.exec('reset role');assert.equal((await db.query("select count(*)::int n from private.register_attempts where client_hash=encode(sha256(convert_to('203.0.113.10','UTF8')),'hex')")).rows[0].n,2);
 assert.equal((await db.query("select count(*)::int n from private.register_attempts where client_hash like '203.%'")).rows[0].n,0);
 await db.query("select set_config('request.headers','',false)");
 await as('authenticated',president);const bulk=await rpc('public.admin_cancel_many($1::bigint[])',[[x1.record.id,x2.record.id,b.record.id,999999,x1.record.id]]);
 assert.deepEqual(bulk.cancelled,[x1.record.id,x2.record.id]);assert.deepEqual(bulk.skipped,[b.record.id,999999]);
 await assert.rejects(rpc('public.admin_cancel_many($1::bigint[])',[[]]),/格式/);
 const afterBulk=await rpc('public.admin_records()');assert.equal(afterBulk.audit.filter(a=>a.action==='cancel'&&a.details.bulk===true).length,2);
 assert.ok(afterBulk.records.every(r=>![x1.record.id,x2.record.id].includes(r.id)||r.status==='cancelled'));
 const dump=await rpc('public.admin_export()');assert.equal(dump.exportedBy,'president@example.test');assert.equal(dump.records.length,afterBulk.records.length);
 assert.ok(dump.records.every(r=>typeof r.token_hash==='string'));assert.deepEqual(dump.admins.sort(),['president@example.test','vice@example.test']);
 assert.equal(dump.opening.outstanding,2);assert.equal(dump.settings.total,6);
 assert.equal((await rpc('public.admin_records()')).audit[0].action,'export');
 await as('anon');assert.ok(!JSON.stringify(await rpc('public.summary()')).includes('token_hash'));
 }finally{await db.close();}
});
