import { createHash, randomUUID } from 'node:crypto';

const digest = value => createHash('sha256').update(value).digest('hex');
const error = (status, message) => { const e = new Error(message); e.status = status; throw e; };
const object = (value, keys) => {
  if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).some(key => !keys.includes(key))) error(400, '請求欄位不正確');
  return value;
};
const string = (value, max, label, required = true, multiline = false) => {
  if (typeof value !== 'string' || value.length > max || (multiline ? /[\x00-\x09\x0b\x0c\x0e-\x1f]/ : /[\x00-\x1f]/).test(value) || (required && !value.trim())) error(400, `${label}格式不正確`);
  return value.trim();
};
const uuid = value => { if (typeof value !== 'string' || !/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/i.test(value)) error(400, '識別碼格式不正確'); return value.toLowerCase(); };
const token = value => { if (typeof value !== 'string' || !/^[a-f\d]{64}$/i.test(value)) error(401, '社員憑證無效'); return value.toLowerCase(); };
const time = value => { if (typeof value !== 'string' || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?(?:Z|[+-]\d\d:\d\d)$/.test(value) || !Number.isFinite(Date.parse(value))) error(400, '時間格式不正確'); return new Date(value).toISOString(); };
const checks = (value, allTrue = false) => {
  object(value, ['frame', 'tires', 'brakes', 'gears', 'accessories']);
  const names = ['frame', 'tires', 'brakes', 'gears', 'accessories'];
  if (names.some(k => typeof value[k] !== 'boolean' || (allTrue && !value[k]))) error(400, '車況檢查項目不完整');
  return Object.fromEntries(names.map(k => [k, value[k]]));
};
const slots = ['left', 'right', 'drivetrain', 'damage'];
const maxPhotoBytes = 8 * 1024 * 1024;
const photoBudgetBytes = 192 * 1024 * 1024;
const photoBuffer = (mime, data) => {
  if (!['image/jpeg', 'image/png', 'image/webp'].includes(mime) || typeof data !== 'string' || data.length > Math.ceil(8 * 1024 * 1024 / 3) * 4 || /[^A-Za-z\d+/=]/.test(data)) error(400, '照片格式不正確');
  const bytes = Buffer.from(data, 'base64');
  if(bytes.toString('base64')!==data) error(400, '照片格式不正確');
  if (!bytes.length || bytes.length > 8 * 1024 * 1024) error(413, '照片超過 8 MiB');
  const magic = mime === 'image/jpeg' ? bytes.length >= 4 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff : mime === 'image/png' ? bytes.length >= 33 && bytes.subarray(0, 8).equals(Buffer.from('89504e470d0a1a0a', 'hex')) && bytes.readUInt32BE(8) === 13 && bytes.toString('ascii', 12, 16) === 'IHDR' && bytes.readUInt32BE(16) > 0 && bytes.readUInt32BE(20) > 0 && bytes.readUInt32BE(16) <= 10000 && bytes.readUInt32BE(20) <= 10000 : bytes.length >= 12 && bytes.toString('ascii', 0, 4) === 'RIFF' && bytes.toString('ascii', 8, 12) === 'WEBP';
  if (!magic) error(400, '照片內容與格式不符');
  return bytes;
};

export function createLifecycle(db) {
  db.exec('PRAGMA foreign_keys=ON');
  db.exec(`
    CREATE TABLE IF NOT EXISTS lifecycle_assets(id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('bike','accessory')), state TEXT NOT NULL CHECK(state IN ('available','inspection','maintenance','retired')), createdAt TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_members(id TEXT PRIMARY KEY, studentId TEXT NOT NULL UNIQUE, name TEXT NOT NULL, contact TEXT NOT NULL, validUntil TEXT NOT NULL, active INTEGER NOT NULL, tokenHash TEXT UNIQUE NOT NULL, createdAt TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_settings(id INTEGER PRIMARY KEY CHECK(id=1), location TEXT NOT NULL DEFAULT '', instructions TEXT NOT NULL DEFAULT '', terms TEXT NOT NULL DEFAULT '', termsVersion TEXT NOT NULL DEFAULT '');
    INSERT OR IGNORE INTO lifecycle_settings(id) VALUES(1);
    CREATE TABLE IF NOT EXISTS lifecycle_reservations(id TEXT PRIMARY KEY, memberId TEXT NOT NULL REFERENCES lifecycle_members(id), borrower TEXT NOT NULL DEFAULT '{}', start TEXT NOT NULL, end TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('reserved','in_use','returned','inspection','cancelled')), createdAt TEXT NOT NULL, pickedUpAt TEXT, returnedAt TEXT);
    CREATE TABLE IF NOT EXISTS lifecycle_reservation_assets(reservationId TEXT NOT NULL REFERENCES lifecycle_reservations(id), assetId TEXT NOT NULL REFERENCES lifecycle_assets(id), PRIMARY KEY(reservationId,assetId));
    CREATE INDEX IF NOT EXISTS lifecycle_reservation_asset_lookup ON lifecycle_reservation_assets(assetId);
    CREATE TABLE IF NOT EXISTS lifecycle_inspections(id TEXT PRIMARY KEY, reservationId TEXT NOT NULL REFERENCES lifecycle_reservations(id), phase TEXT NOT NULL CHECK(phase IN ('pickup','return')), checks TEXT NOT NULL, notes TEXT NOT NULL, abnormal INTEGER NOT NULL, createdAt TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_photos(id TEXT PRIMARY KEY, reservationId TEXT NOT NULL REFERENCES lifecycle_reservations(id), assetId TEXT NOT NULL REFERENCES lifecycle_assets(id), phase TEXT NOT NULL CHECK(phase IN ('pickup','return')), slot TEXT NOT NULL CHECK(slot IN ('left','right','drivetrain','damage')), mime TEXT NOT NULL, size INTEGER NOT NULL, sha256 TEXT NOT NULL, uploadedAt TEXT NOT NULL, data BLOB NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_signatures(reservationId TEXT PRIMARY KEY REFERENCES lifecycle_reservations(id), name TEXT NOT NULL, terms TEXT NOT NULL, termsVersion TEXT NOT NULL, signedAt TEXT NOT NULL, image TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_requests(requestId TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, payloadHash TEXT NOT NULL, receipt TEXT NOT NULL, PRIMARY KEY(actor,requestId));
    CREATE TABLE IF NOT EXISTS lifecycle_events(id INTEGER PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, reservationId TEXT, at TEXT NOT NULL, details TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lifecycle_notifications(id INTEGER PRIMARY KEY, reservationId TEXT NOT NULL, createdAt TEXT NOT NULL, resolvedAt TEXT, details TEXT NOT NULL);
  `);
  if (!db.prepare('PRAGMA table_info(lifecycle_reservations)').all().some(c => c.name === 'borrower')) db.exec("ALTER TABLE lifecycle_reservations ADD COLUMN borrower TEXT NOT NULL DEFAULT '{}'");
  // Self-service bookings: the device keeps a random key (only its hash is stored) and an officer approves before pickup.
  const reservationColumns = db.prepare('PRAGMA table_info(lifecycle_reservations)').all().map(c => c.name);
  for (const [name, ddl] of [['accessHash', 'TEXT'], ['approval', "TEXT NOT NULL DEFAULT 'approved' CHECK(approval IN ('approved','pending'))"], ['approvedAt', 'TEXT']]) if (!reservationColumns.includes(name)) db.exec(`ALTER TABLE lifecycle_reservations ADD COLUMN ${name} ${ddl}`);
  db.exec('CREATE UNIQUE INDEX IF NOT EXISTS lifecycle_reservation_access ON lifecycle_reservations(accessHash) WHERE accessHash IS NOT NULL');
  const requestKey = db.prepare('PRAGMA table_info(lifecycle_requests)').all().filter(c => c.pk).sort((a, b) => a.pk - b.pk).map(c => c.name);
  if (requestKey.join(',') !== 'actor,requestId') {
    db.exec('BEGIN IMMEDIATE');
    try {
      db.exec(`CREATE TABLE lifecycle_requests_rekey(requestId TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, payloadHash TEXT NOT NULL, receipt TEXT NOT NULL, PRIMARY KEY(actor,requestId));
        INSERT INTO lifecycle_requests_rekey SELECT requestId,actor,action,payloadHash,receipt FROM lifecycle_requests;
        DROP TABLE lifecycle_requests;
        ALTER TABLE lifecycle_requests_rekey RENAME TO lifecycle_requests;`);
      db.exec('COMMIT');
    } catch (e) { db.exec('ROLLBACK'); throw e; }
  }
  for (const table of ['lifecycle_photos', 'lifecycle_signatures', 'lifecycle_inspections', 'lifecycle_requests', 'lifecycle_events']) {
    db.exec(`CREATE TRIGGER IF NOT EXISTS ${table}_immutable_update BEFORE UPDATE ON ${table} BEGIN SELECT RAISE(ABORT,'immutable evidence'); END;
      CREATE TRIGGER IF NOT EXISTS ${table}_immutable_delete BEFORE DELETE ON ${table} BEGIN SELECT RAISE(ABORT,'immutable evidence'); END;`);
  }
  const run = fn => { db.exec('BEGIN IMMEDIATE'); try { const value = fn(); db.exec('COMMIT'); return value; } catch (e) { db.exec('ROLLBACK'); throw e; } };
  const setting = () => db.prepare('SELECT location,terms,termsVersion FROM lifecycle_settings WHERE id=1').get();
  const assets = () => db.prepare('SELECT id,code,name,kind,state FROM lifecycle_assets ORDER BY code').all();
  const memberPublic = row => row && ({ id: row.id, studentId: row.studentId, name: row.name, contact: row.contact, validUntil: row.validUntil, active: !!row.active });
  const members = () => db.prepare('SELECT * FROM lifecycle_members ORDER BY studentId').all().map(memberPublic);
  const assetIds = id => db.prepare('SELECT assetId FROM lifecycle_reservation_assets WHERE reservationId=? ORDER BY assetId').all(id).map(r => r.assetId);
  const photos = id => db.prepare('SELECT id,reservationId,assetId,phase,slot,mime,size,sha256,uploadedAt FROM lifecycle_photos WHERE reservationId=? ORDER BY uploadedAt,id').all(id);
  const reservation = row => {
    if (!row) return null;
    const inspections = db.prepare('SELECT phase,checks,notes,abnormal,createdAt FROM lifecycle_inspections WHERE reservationId=? ORDER BY createdAt,id').all(row.id).map(i => ({ ...i, checks: JSON.parse(i.checks), abnormal: !!i.abnormal }));
    const { accessHash, ...rest } = row;
    return { ...rest, selfService: !!accessHash, borrower: JSON.parse(row.borrower), assetIds: assetIds(row.id), inspections, photos: photos(row.id), signature: db.prepare('SELECT name,terms,termsVersion,signedAt,image FROM lifecycle_signatures WHERE reservationId=?').get(row.id) || null };
  };
  const reservations = (memberId = null) => db.prepare(`SELECT * FROM lifecycle_reservations ${memberId ? 'WHERE memberId=? ' : ''}ORDER BY createdAt DESC,id`).all(...(memberId ? [memberId] : [])).map(reservation);
  const event = (actor, action, reservationId, details = {}) => db.prepare('INSERT INTO lifecycle_events(actor,action,reservationId,at,details) VALUES(?,?,?,?,?)').run(actor, action, reservationId, new Date().toISOString(), JSON.stringify(details));
  // An officer-issued member credential sees all of that member's bookings; a booking key sees only its own booking.
  const principal = raw => { const hash = digest(token(raw)); const found = db.prepare('SELECT * FROM lifecycle_members WHERE tokenHash=?').get(hash); if (found) return { member: found, scope: null }; const booking = db.prepare('SELECT id,memberId FROM lifecycle_reservations WHERE accessHash=?').get(hash); if (!booking) error(401, '社員憑證無效'); return { member: db.prepare('SELECT * FROM lifecycle_members WHERE id=?').get(booking.memberId), scope: booking.id }; };
  const selfServiceName = row => JSON.parse(row.borrower || '{}').name;
  const eligible = (member, end = new Date().toISOString()) => { if (!member.active || member.validUntil < end) error(403, '社員資格未生效或已過期'); };
  const own = (member, id, scope = null) => { const row = db.prepare('SELECT * FROM lifecycle_reservations WHERE id=? AND memberId=?').get(uuid(id), member.id); if (!row || (scope && row.id !== scope)) error(404, '查無借車紀錄'); return row; };
  // Shared admission checks for officer-issued credentials and self-service applications.
  const admit = (payload, member, studentId) => { const start = time(payload.start), end = time(payload.end), now = new Date().toISOString(); if (start < now || end <= start || Date.parse(end) - Date.parse(start) > 5 * 86400000) error(400, '預約時間不正確'); const policy = setting(); if (!policy.location || !policy.terms) error(409, '幹部尚未設定取車資訊與借車規範'); if (!Array.isArray(payload.assetIds) || payload.assetIds.length < 1 || payload.assetIds.length > 20) error(400, '資產清單不正確'); const ids = payload.assetIds.map(uuid); if (new Set(ids).size !== ids.length) error(400, '資產重複'); const selected = ids.map(id => db.prepare('SELECT * FROM lifecycle_assets WHERE id=?').get(id)); if (selected.some(a => !a || a.state !== 'available') || selected.filter(a => a.kind === 'bike').length !== 1 || ids.some(id => blocks(id, start, end))) error(409, '車輛或配件不可預約'); if ((member && db.prepare("SELECT 1 FROM lifecycle_reservations WHERE memberId=? AND status IN ('reserved','in_use','inspection') LIMIT 1").get(member.id)) || db.prepare("SELECT 1 FROM records WHERE studentId=? AND status IN ('waiting','borrowed') LIMIT 1").get(studentId)) error(409, '已有有效借車或登記紀錄'); const capacity = storage(); if (capacity.usedBytes + capacity.reservedBytes + 8 * maxPhotoBytes > photoBudgetBytes) error(409, '照片保存空間不足，暫停接受新預約，請聯絡幹部'); return { start, end, ids, now }; };
  const request = (actor, action, payload, work) => {
    const id = uuid(payload.requestId);
    const fingerprint = digest(JSON.stringify(payload));
    return run(() => {
      const previous = db.prepare('SELECT action,payloadHash,receipt FROM lifecycle_requests WHERE actor=? AND requestId=?').get(actor, id);
      if (previous) { if (previous.action !== action || previous.payloadHash !== fingerprint) error(409, '操作識別碼已用於不同內容'); return JSON.parse(previous.receipt); }
      const receipt = work();
      db.prepare('INSERT INTO lifecycle_requests VALUES(?,?,?,?,?)').run(id, actor, action, fingerprint, JSON.stringify(receipt));
      return receipt;
    });
  };
  const requirePhotos = (row, phase) => {
    const bike = db.prepare("SELECT a.id FROM lifecycle_assets a JOIN lifecycle_reservation_assets ra ON ra.assetId=a.id WHERE ra.reservationId=? AND a.kind='bike'").get(row.id);
    if (!bike || slots.some(slot => !db.prepare('SELECT id FROM lifecycle_photos WHERE reservationId=? AND assetId=? AND phase=? AND slot=? LIMIT 1').get(row.id, bike.id, phase, slot))) error(409, '請先完成四項車輛照片');
  };
  const activeAsset = id => !!db.prepare("SELECT 1 FROM lifecycle_reservation_assets ra JOIN lifecycle_reservations r ON r.id=ra.reservationId WHERE ra.assetId=? AND r.status IN ('reserved','in_use','inspection') LIMIT 1").get(id);
  const availableBikes = () => db.prepare("SELECT COUNT(*) n FROM lifecycle_assets WHERE kind='bike' AND state='available'").get().n;
  const legacyOccupied = () => db.prepare("SELECT COUNT(*) n FROM records WHERE status='borrowed'").get().n + db.prepare('SELECT outstanding FROM opening_loans WHERE id=1').get().outstanding;
  const storage = () => {
    const usedBytes = db.prepare('SELECT COALESCE(SUM(size),0) n FROM lifecycle_photos').get().n;
    const active = db.prepare("SELECT id,status FROM lifecycle_reservations WHERE status IN ('reserved','in_use')").all();
    let reservedSlots = 0;
    for (const row of active) {
      const covered = db.prepare('SELECT phase,COUNT(DISTINCT slot) n FROM lifecycle_photos WHERE reservationId=? GROUP BY phase').all(row.id);
      const count = phase => covered.find(p => p.phase === phase)?.n ?? 0;
      if (row.status === 'reserved') reservedSlots += 4 - count('pickup');
      reservedSlots += 4 - count('return');
    }
    return { usedBytes, reservedBytes: reservedSlots * maxPhotoBytes, budgetBytes: photoBudgetBytes, maxPhotoBytes };
  };
  const blocks = (id, start, end) => !!db.prepare("SELECT 1 FROM lifecycle_reservation_assets ra JOIN lifecycle_reservations r ON r.id=ra.reservationId WHERE ra.assetId=? AND (r.status IN ('in_use','inspection') OR (r.status='reserved' AND r.start<? AND r.end>?)) LIMIT 1").get(id, end, start);
  const readPhoto = (id, member = null) => {
    const photo = db.prepare('SELECT * FROM lifecycle_photos WHERE id=?').get(uuid(id));
    if (!photo || (member && !db.prepare('SELECT 1 FROM lifecycle_reservations WHERE id=? AND memberId=?').get(photo.reservationId, member.id))) error(404, '查無照片');
    const { data, ...meta } = photo;
    return { photo: { ...meta, data: Buffer.from(data).toString('base64') } };
  };
  const calendar = payload => {
    object(payload, ['start', 'end']); const start = time(payload.start), end = time(payload.end);
    if (end <= start || Date.parse(end) - Date.parse(start) > 42 * 86400000) error(400, '日曆範圍不正確');
    const bookings = db.prepare("SELECT * FROM lifecycle_reservations WHERE (status='reserved' AND start<? AND end>?) OR status IN ('in_use','inspection') ORDER BY start,id").all(end, start).map(row => ({ id: row.id, assetIds: assetIds(row.id), start: row.start, end: row.end, status: row.status, pending: row.approval === 'pending' }));
    return { assets: assets(), bookings, settings: setting(), updatedAt: new Date().toISOString() };
  };
  function handle(action, rawToken, payload = {}, actor = null) {
    if (typeof action !== 'string' || action.length > 40) error(400, '操作格式不正確');
    if (actor) {
      if (action === 'list') { object(payload, []); return { assets: assets(), members: members(), reservations: reservations(), settings: setting(), storage: storage(), events: db.prepare('SELECT * FROM lifecycle_events ORDER BY id DESC LIMIT 500').all().map(e => ({ ...e, details: JSON.parse(e.details) })), notifications: db.prepare('SELECT * FROM lifecycle_notifications ORDER BY id DESC').all().map(n => ({ ...n, details: JSON.parse(n.details) })) }; }
      if (action === 'photo_read') { object(payload, ['id']); return readPhoto(payload.id); }
      if (action === 'export') return run(() => { object(payload, []); event(actor, 'export', null); return { exportedAt: new Date().toISOString(), exportedBy: actor, settings: setting(), assets: db.prepare('SELECT * FROM lifecycle_assets').all(), members: db.prepare('SELECT * FROM lifecycle_members').all(), reservations: db.prepare('SELECT * FROM lifecycle_reservations').all(), reservationAssets: db.prepare('SELECT * FROM lifecycle_reservation_assets').all(), inspections: db.prepare('SELECT * FROM lifecycle_inspections').all(), photos: db.prepare('SELECT * FROM lifecycle_photos').all().map(({ data, ...p }) => ({ ...p, data: Buffer.from(data).toString('base64') })), signatures: db.prepare('SELECT * FROM lifecycle_signatures').all(), requests: db.prepare('SELECT * FROM lifecycle_requests').all(), events: db.prepare('SELECT * FROM lifecycle_events').all(), notifications: db.prepare('SELECT * FROM lifecycle_notifications').all() }; });
      if (action === 'settings') return run(() => { object(payload, ['location', 'instructions', 'terms']); /* instructions: retired field; older cached pages may still send it, ignored */ const location = string(payload.location, 500, '社辦位置'), terms = string(payload.terms, 10000, '借車規範', true, true), termsVersion = digest(terms); db.prepare('UPDATE lifecycle_settings SET location=?,terms=?,termsVersion=? WHERE id=1').run(location, terms, termsVersion); event(actor, 'settings', null, { termsVersion }); return { settings: setting() }; });
      if (action === 'asset') return run(() => { object(payload, ['id', 'code', 'name', 'kind', 'state', 'reason']); const id = payload.id === undefined ? randomUUID() : uuid(payload.id), code = string(payload.code, 50, '車輛編號'), name = string(payload.name, 100, '名稱'), reason = string(payload.reason, 500, '原因', true, true); if (!['bike', 'accessory'].includes(payload.kind) || !['available', 'inspection', 'maintenance', 'retired'].includes(payload.state)) error(400, '資產狀態不正確'); const old = db.prepare('SELECT * FROM lifecycle_assets WHERE id=?').get(id); if (db.prepare('SELECT 1 FROM lifecycle_assets WHERE code=? AND id<>?').get(code, id)) error(409, '車輛或配件編號已存在'); if (old && (old.code !== code || old.kind !== payload.kind) && db.prepare('SELECT 1 FROM lifecycle_reservation_assets WHERE assetId=? LIMIT 1').get(id)) error(409, '已有借車歷史的車號或類型不可變更'); if (old && activeAsset(id) && (old.kind !== payload.kind || old.state !== payload.state || old.code !== code)) error(409, '此資產仍有預約或借用'); const total = db.prepare('SELECT total FROM settings WHERE id=1').get().total; const addingAvailable = payload.kind === 'bike' && payload.state === 'available' && !(old?.kind === 'bike' && old.state === 'available'); if (addingAvailable && (total === null || legacyOccupied() + availableBikes() + 1 > total)) error(409, '請先核對社車總數與舊借用紀錄'); if (old) db.prepare('UPDATE lifecycle_assets SET code=?,name=?,kind=?,state=? WHERE id=?').run(code, name, payload.kind, payload.state, id); else db.prepare('INSERT INTO lifecycle_assets VALUES(?,?,?,?,?,?)').run(id, code, name, payload.kind, payload.state, new Date().toISOString()); event(actor, 'asset', null, { id, reason, state: payload.state }); return { asset: db.prepare('SELECT id,code,name,kind,state FROM lifecycle_assets WHERE id=?').get(id) }; });
      if (action === 'member') return run(() => { object(payload, ['id', 'studentId', 'name', 'contact', 'validUntil', 'active', 'token', 'reason']); const id = payload.id === undefined ? randomUUID() : uuid(payload.id), studentId = string(payload.studentId, 30, '學號').toUpperCase(), name = string(payload.name, 80, '姓名'), contact = string(payload.contact, 200, '聯絡方式'), validUntil = time(payload.validUntil), reason = string(payload.reason, 500, '原因', true, true); if (!/^[A-Z\d-]+$/.test(studentId) || typeof payload.active !== 'boolean') error(400, '社員資料不正確'); const old = db.prepare('SELECT * FROM lifecycle_members WHERE id=?').get(id); if (old && (old.studentId !== studentId || old.name !== name) && db.prepare("SELECT 1 FROM lifecycle_reservations WHERE memberId=? AND status IN ('reserved','in_use','inspection') LIMIT 1").get(id)) error(409, '有效借車期間不可變更社員姓名或學號'); if (!old && payload.token === undefined) error(400, '建立社員須提供新憑證'); const tokenHash = payload.token === undefined ? old.tokenHash : digest(token(payload.token)); if (db.prepare('SELECT 1 FROM lifecycle_members WHERE studentId=? AND id<>?').get(studentId, id) || db.prepare('SELECT 1 FROM lifecycle_members WHERE tokenHash=? AND id<>?').get(tokenHash, id)) error(409, '學號或憑證已存在'); if (old) db.prepare('UPDATE lifecycle_members SET studentId=?,name=?,contact=?,validUntil=?,active=?,tokenHash=? WHERE id=?').run(studentId, name, contact, validUntil, +payload.active, tokenHash, id); else db.prepare('INSERT INTO lifecycle_members VALUES(?,?,?,?,?,?,?,?)').run(id, studentId, name, contact, validUntil, +payload.active, tokenHash, new Date().toISOString()); event(actor, 'member', null, { id, reason, active: payload.active, before: old ? { studentId: old.studentId, name: old.name, contact: old.contact, validUntil: old.validUntil, active: !!old.active } : null, after: { studentId, name, contact, validUntil, active: payload.active } }); return { member: memberPublic(db.prepare('SELECT * FROM lifecycle_members WHERE id=?').get(id)) }; });
      if (action === 'approve' || action === 'access') return request(`admin:${actor}`, action, payload, () => { object(payload, action === 'approve' ? ['requestId', 'reservationId'] : ['requestId', 'reservationId', 'key']); const row = db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(uuid(payload.reservationId)); if (!row) error(404, '查無借車紀錄'); const now = new Date().toISOString(); if (action === 'approve') { if (row.status !== 'reserved' || row.approval !== 'pending') error(409, '這筆預約目前不需要同意'); db.prepare("UPDATE lifecycle_reservations SET approval='approved',approvedAt=? WHERE id=?").run(now, row.id); } else { if (!row.accessHash || !['reserved', 'in_use'].includes(row.status)) error(409, '只有進行中的自助預約可以重新產生取還車碼'); const accessHash = digest(token(payload.key)); if (db.prepare('SELECT 1 FROM lifecycle_members WHERE tokenHash=?').get(accessHash)) error(409, '請重新產生'); db.prepare('UPDATE lifecycle_reservations SET accessHash=? WHERE id=?').run(accessHash, row.id); } event(actor, action, row.id); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(row.id)) }; });
      if (action === 'cancel' || action === 'resolve') return request(`admin:${actor}`, action, payload, () => { object(payload, action === 'cancel' ? ['requestId', 'reservationId', 'reason'] : ['requestId', 'reservationId', 'reason', 'state']); const row = db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(uuid(payload.reservationId)); if (!row) error(404, '查無借車紀錄'); const reason = string(payload.reason, 500, '原因', true, true); if (action === 'cancel') { if (row.status !== 'reserved') error(409, '目前狀態不允許取消'); db.prepare("UPDATE lifecycle_reservations SET status='cancelled' WHERE id=?").run(row.id); } else { if (row.status !== 'inspection' || !['available', 'maintenance'].includes(payload.state)) error(409, '目前狀態不允許結案'); if (payload.state === 'maintenance' && db.prepare("SELECT 1 FROM lifecycle_reservation_assets ra JOIN lifecycle_reservation_assets other ON other.assetId=ra.assetId JOIN lifecycle_reservations future ON future.id=other.reservationId WHERE ra.reservationId=? AND future.id<>? AND future.status='reserved' LIMIT 1").get(row.id, row.id)) error(409, '仍有其他有效預約，請先處理後續預約'); if (payload.state === 'available') { const total = db.prepare('SELECT total FROM settings WHERE id=1').get().total; const bikes = db.prepare("SELECT COUNT(*) n FROM lifecycle_reservation_assets ra JOIN lifecycle_assets a ON a.id=ra.assetId WHERE ra.reservationId=? AND a.kind='bike' AND a.state<>'available'").get(row.id).n; if (total === null || legacyOccupied() + availableBikes() + bikes > total) error(409, '車輛總數與舊借用紀錄尚未核對'); } db.prepare("UPDATE lifecycle_reservations SET status='returned' WHERE id=?").run(row.id); for (const id of assetIds(row.id)) db.prepare('UPDATE lifecycle_assets SET state=? WHERE id=?').run(payload.state, id); db.prepare('UPDATE lifecycle_notifications SET resolvedAt=? WHERE reservationId=? AND resolvedAt IS NULL').run(new Date().toISOString(), row.id); } event(actor, action, row.id, { reason, state: payload.state }); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(row.id)) }; });
      error(404, '找不到操作');
    }
    if (action === 'calendar') return calendar(payload);
    if (action === 'apply') { object(payload, ['requestId', 'studentId', 'name', 'assetIds', 'start', 'end', 'key']); const accessHash = digest(token(payload.key)); return request(`apply:${accessHash}`, action, payload, () => { const studentId = string(payload.studentId, 30, '學號').toUpperCase(), name = string(payload.name, 80, '姓名'); if (!/^[A-Z\d-]+$/.test(studentId)) error(400, '學號格式不正確'); let member = db.prepare('SELECT * FROM lifecycle_members WHERE studentId=?').get(studentId); if (member && !member.active) error(403, '此學號的借用資格已停用，請聯絡幹部'); if (db.prepare('SELECT 1 FROM lifecycle_members WHERE tokenHash=?').get(accessHash) || db.prepare('SELECT 1 FROM lifecycle_reservations WHERE accessHash=?').get(accessHash)) error(409, '請重新送出預約'); const { start, end, ids, now } = admit(payload, member, studentId); if (!member) { const id = randomUUID(); db.prepare('INSERT INTO lifecycle_members VALUES(?,?,?,?,?,?,?,?)').run(id, studentId, name, '', '2099-12-31T00:00:00.000Z', 1, digest(randomUUID() + randomUUID()), now); member = db.prepare('SELECT * FROM lifecycle_members WHERE id=?').get(id); } const id = randomUUID(); db.prepare("INSERT INTO lifecycle_reservations(id,memberId,borrower,start,end,status,createdAt,accessHash,approval) VALUES(?,?,?,?,?,'reserved',?,?,'pending')").run(id, member.id, JSON.stringify({ studentId, name, contact: '' }), start, end, now, accessHash); for (const assetId of ids) db.prepare('INSERT INTO lifecycle_reservation_assets VALUES(?,?)').run(id, assetId); event(member.id, action, id, { selfService: true }); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(id)) }; }); }
    const { member, scope } = principal(rawToken);
    if (action === 'me') { object(payload, []); return { member: memberPublic(member), reservations: reservations(member.id).filter(r => !scope || r.id === scope), settings: setting() }; }
    if (action === 'photo_read') { object(payload, ['id']); const result = readPhoto(payload.id, member); if (scope && result.photo.reservationId !== scope) error(404, '查無照片'); return result; }
    if (action === 'reserve') return request(`member:${member.id}`, action, payload, () => { object(payload, ['requestId', 'assetIds', 'start', 'end']); if (scope) error(403, '請使用預約表單送出新的預約'); eligible(member, time(payload.end)); const { start, end, ids, now } = admit(payload, member, member.studentId); const id = randomUUID(); db.prepare("INSERT INTO lifecycle_reservations(id,memberId,borrower,start,end,status,createdAt) VALUES(?,?,?,?,?,'reserved',?)").run(id, member.id, JSON.stringify({ studentId: member.studentId, name: member.name, contact: member.contact }), start, end, now); for (const assetId of ids) db.prepare('INSERT INTO lifecycle_reservation_assets VALUES(?,?)').run(id, assetId); event(member.id, action, id); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(id)) }; });
    if (action === 'photo') return request(`member:${member.id}`, action, payload, () => { object(payload, ['requestId', 'reservationId', 'assetId', 'phase', 'slot', 'mime', 'data']); const row = own(member, payload.reservationId, scope), assetId = uuid(payload.assetId), now = new Date().toISOString(); if (payload.phase === 'pickup' && row.approval !== 'approved') error(409, '幹部尚未同意此預約'); if (!['pickup', 'return'].includes(payload.phase) || !slots.includes(payload.slot)) error(400, '拍攝項目不正確'); if (!db.prepare("SELECT 1 FROM lifecycle_reservation_assets ra JOIN lifecycle_assets a ON a.id=ra.assetId WHERE ra.reservationId=? AND a.id=? AND a.kind='bike'").get(row.id, assetId)) error(400, '照片須對應借用車輛'); if (payload.phase === 'pickup' ? row.status !== 'reserved' || now < row.start || now >= row.end : row.status !== 'in_use') error(409, '目前不允許上傳此階段照片'); if (db.prepare('SELECT COUNT(*) n FROM lifecycle_photos WHERE reservationId=? AND phase=?').get(row.id, payload.phase).n >= 12) error(409, '本階段照片已達 12 張上限，請聯絡幹部'); const bytes = photoBuffer(payload.mime, payload.data), currentStorage = storage(); const covered = db.prepare('SELECT 1 FROM lifecycle_photos WHERE reservationId=? AND phase=? AND slot=? LIMIT 1').get(row.id, payload.phase, payload.slot); const remainingAfter = currentStorage.reservedBytes - (covered ? 0 : maxPhotoBytes); if (currentStorage.usedBytes + bytes.length + remainingAfter > photoBudgetBytes) error(409, '照片保存空間不足，請聯絡幹部'); const id = randomUUID(); db.prepare('INSERT INTO lifecycle_photos VALUES(?,?,?,?,?,?,?,?,?,?)').run(id, row.id, assetId, payload.phase, payload.slot, payload.mime, bytes.length, digest(bytes), now, bytes); event(member.id, 'photo', row.id, { photoId: id, phase: payload.phase, slot: payload.slot }); return { photo: db.prepare('SELECT id,reservationId,assetId,phase,slot,mime,size,sha256,uploadedAt FROM lifecycle_photos WHERE id=?').get(id) }; });
    if (action === 'pickup') return request(`member:${member.id}`, action, payload, () => { object(payload, ['requestId', 'reservationId', 'checks', 'notes', 'signature']); const row = own(member, payload.reservationId, scope), now = new Date().toISOString(); if (row.approval !== 'approved') error(409, '幹部尚未同意此預約'); if (row.accessHash) { if (!member.active) error(403, '社員資格未生效或已過期'); } else eligible(member, row.end); const signer = selfServiceName(row) || member.name; if (row.status !== 'reserved' || now < row.start || now >= row.end) error(409, '尚未到取車時間或預約已結束'); checks(payload.checks, true); for (const assetId of assetIds(row.id)) { const asset = db.prepare('SELECT state FROM lifecycle_assets WHERE id=?').get(assetId); if (asset?.state !== 'available' || db.prepare("SELECT 1 FROM lifecycle_reservation_assets ra JOIN lifecycle_reservations r ON r.id=ra.reservationId WHERE ra.assetId=? AND r.id<>? AND r.status IN ('in_use','inspection') LIMIT 1").get(assetId, row.id)) error(409, '車輛或配件目前不可取用，請聯絡幹部'); } requirePhotos(row, 'pickup'); if (db.prepare("SELECT 1 FROM lifecycle_reservations WHERE memberId=? AND status='in_use' LIMIT 1").get(member.id)) error(409, '已有使用中車輛'); const inventory = db.prepare('SELECT total FROM settings WHERE id=1').get().total; const occupied = db.prepare("SELECT COUNT(*) n FROM records WHERE status='borrowed'").get().n + db.prepare('SELECT outstanding FROM opening_loans WHERE id=1').get().outstanding + db.prepare("SELECT COUNT(*) n FROM lifecycle_reservations WHERE status='in_use'").get().n; if (inventory === null || occupied >= inventory) error(409, '目前沒有可交付的社車'); const notes = string(payload.notes, 1000, '車況備註', false, true); object(payload.signature, ['name', 'accepted', 'termsVersion', 'image']); const policy = setting(), sig = payload.signature; if (string(sig.name, 80, '簽署姓名') !== signer || sig.accepted !== true || sig.termsVersion !== policy.termsVersion || !policy.terms) error(409, '簽署內容與目前借車規範不符'); if (typeof sig.image !== 'string' || !sig.image.startsWith('data:image/png;base64,')) error(400, '請提供簽名圖像'); const bytes = photoBuffer('image/png', sig.image.slice(22)); if (bytes.length < 100 || bytes.length > 256 * 1024 || bytes.readUInt32BE(16) < 100 || bytes.readUInt32BE(20) < 30) error(400, '簽名圖像無效或過大'); const inspectionId = randomUUID(); db.prepare('INSERT INTO lifecycle_inspections VALUES(?,?,?,?,?,?,?)').run(inspectionId, row.id, 'pickup', JSON.stringify(payload.checks), notes, 0, now); db.prepare('INSERT INTO lifecycle_signatures VALUES(?,?,?,?,?,?)').run(row.id, signer, policy.terms, policy.termsVersion, now, sig.image); db.prepare("UPDATE lifecycle_reservations SET status='in_use',pickedUpAt=? WHERE id=?").run(now, row.id); event(member.id, 'pickup', row.id); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(row.id)) }; });
    if (action === 'return') return request(`member:${member.id}`, action, payload, () => { object(payload, ['requestId', 'reservationId', 'checks', 'notes', 'abnormal']); const row = own(member, payload.reservationId, scope), now = new Date().toISOString(); if (row.status !== 'in_use') error(409, '目前不允許還車'); const values = checks(payload.checks); if (typeof payload.abnormal !== 'boolean') error(400, '異常狀態不正確'); requirePhotos(row, 'return'); const notes = string(payload.notes, 1000, '車況備註', false, true), abnormal = payload.abnormal || Object.values(values).some(v => !v), status = abnormal ? 'inspection' : 'returned'; db.prepare('INSERT INTO lifecycle_inspections VALUES(?,?,?,?,?,?,?)').run(randomUUID(), row.id, 'return', JSON.stringify(values), notes, +abnormal, now); db.prepare('UPDATE lifecycle_reservations SET status=?,returnedAt=? WHERE id=?').run(status, now, row.id); if (abnormal) { for (const id of assetIds(row.id)) db.prepare("UPDATE lifecycle_assets SET state='inspection' WHERE id=?").run(id); db.prepare('INSERT INTO lifecycle_notifications(reservationId,createdAt,details) VALUES(?,?,?)').run(row.id, now, JSON.stringify({ notes, checks: values })); } event(member.id, 'return', row.id, { abnormal }); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(row.id)) }; });
    if (action === 'cancel') return request(`member:${member.id}`, action, payload, () => { object(payload, ['requestId', 'reservationId', 'reason']); const row = own(member, payload.reservationId, scope), reason = string(payload.reason, 500, '取消原因', true, true); if (row.status !== 'reserved') error(409, '目前不允許取消'); db.prepare("UPDATE lifecycle_reservations SET status='cancelled' WHERE id=?").run(row.id); event(member.id, 'cancel', row.id, { reason }); return { reservation: reservation(db.prepare('SELECT * FROM lifecycle_reservations WHERE id=?').get(row.id)) }; });
    error(404, '找不到操作');
  }
  return { handle, exportData: actor => handle('export', null, {}, actor) };
}
